# Generated by Django 4.0.3 on 2022-03-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hersteller', models.CharField(max_length=40)),
                ('modell', models.CharField(max_length=40)),
                ('nummernschild', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(choices=[('BESTELLT', 'Bestellt'), ('EINGETROFFEN', 'Eingetroffen'), ('IN_REPARATUR', 'In Reparatur'), ('FAHRBEREIT', 'Fahrbereit')], max_length=30)),
            ],
        ),
    ]
