# Generated by Django 4.0.3 on 2022-04-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='baujahr',
            field=models.IntegerField(default=1970),
            preserve_default=False,
        ),
    ]
